run:
  timeout: 3m
  issues-exit-code: 1
  tests: true

linters-settings:
  revive:
    ignoreGeneratedHeader: true
    severity: warning
    rules:
      - name: exported
        severity: warning
      - name: indent-error-flow
      - name: error-return
      - name: unreachable-code
  gocyclo:
    min-complexity: 15
  gosec:
    severity: medium

linters:
  enable:
    - govet
    - staticcheck
    - revive
    - errcheck
    - ineffassign
    - gosimple
    - unused
    - typecheck
    - gocyclo
    - gosec
    - goconst
  disable:
    - dupl
    - depguard
    - stylecheck

issues:
  exclude-rules:
    - path: _test.go
      linters: [gocyclo]
    - path: internal/server/router.go
      linters: [gocyclo]
    - path: migrations/.*\.sql
      linters: [revive]

output:
  format: colored-line-number
